language: php

php:
  - 5.5.9
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
      - php: hhvm

env:
  - APP_ENV="testing" APP_DEBUG=true SQLITE_DATABASE=":memory:" APP_KEY="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" BUGSNAG_API_KEY=""

sudo: false

install:
  - travis_retry composer install --no-interaction --prefer-source --dev
  - php artisan env
  - php artisan migrate

script: vendor/bin/phpunit

after_failure:
 - cat storage/logs/*.log